### ISSUE TITLE
Endpoint end info not working

### ISSUE THREAD

**Issue by ParticleCore** [tmcw/docbox#133]
In the example of the latest version we can read the end of the http request under "List wobbles"

    GET /wobbles/v1/{username} wobbles:read

https://github.com/tmcw/docbox/blob/master/content/example.md

However, when opening the website itself the `wobbles:read` is nowhere to be found: https://67-53007065-gh.circle-artifacts.com/0/tmp/circle-artifacts.NCC9T6a/index.html?language=cURL#list-wobbles

Wasn't `wobbles:read` suppose to be showing at the end of the endpoint? Just like in this image of a previous version:

![4](https://user-images.githubusercontent.com/9222661/61870291-b886e680-aeab-11e9-8edc-731de8d0ccb8.jpg)

**Comment by tmcw** [comment]
That's a remnant of a previous version that hardcoded that particular style - now that's in custom/index.js

https://github.com/tmcw/docbox/blob/master/src/custom/index.js#L43-L61

You can tweak this to transform URLs however you'd like. The `{wobbles:read}` token was rather custom to one style of authentication (a GitHub API-like scoped permissions system) and wasn't general, so it was replaced with a more generic HTTP method + URL style, and I made sure that it was possible for folks to customize it to taste.
