### ISSUE TITLE
Where is the detailed documentation?

### ISSUE THREAD

**Issue by yingzi20** [tmcw/docbox#135]
I want add navigation at the top of the page, but I do not know hot to achieve it, and I have not find the documentation, where is the detailed documentation of the docbox?

**Comment by tmcw** [comment]
docbox is a React application. I've described how to add and update documentation, and provided examples of using it. Anything like customizing docbox or adding additional UI, like a top-page navigation, is the same as implementing that feature in any other React application, and the documentation you'll need to implement thing is React's documentation: https://reactjs.org/
