### ISSUE TITLE
Questions regarding strong and em

### ISSUE THREAD

**Issue by alexjab** [tmcw/docbox#23]
Hi,

I'm trying to wrap my head around an issue I'm encountering with `**strong**` and `*emphasised*` texts: they are just rendered as vanilla paragraph text on my system, instead of the expected strong and italic text.

I've noticed that the css rules specifically reset the font property of the `strong` and `em` tags (in [css/base.css](https://github.com/tmcw/docbox/blob/95c5d705a19865b59ce9bd0b1a815adbc897e656/css/base.css#L6-L7), and also later on for `strong`), and use bold and italic fonts instead (Open Sans Bold, and Open Sans Italic). While this works well on the Mapbox API page because the aforementioned fonts are served to the visitor, I'm afraid most developers would not want to do the same.

I'm not sure I understand the reason behind this choice, rather than just using vanilla properties of the tags.

Several tweaks may do the trick:
 - don't reset rules for `strong` and `em` (or maybe do `font-family: inherit` instead of `font: inherit`),
 - remove the `font-weight: normal` for `.strong`.

What do you think ?

BR

**Comment by tmcw** [comment]
Yeah, sorry about this. This is the result of an still-present bug in base.css, where it used web fonts incorrectly, in a systematic way that spread the problem around.

I've just implemented #24, which should fix this issue - can you check it out and see if it resolves the problem?

**Comment by alexjab** [comment]
Done ! LGTM !
