### ISSUE TITLE
something wrong after i run build

### ISSUE THREAD

**Issue by yycsrkl** [tmcw/docbox#72]
after i run build, something is not the same with before when i was running start.

this is after i run build
![default](https://user-images.githubusercontent.com/15883911/35902124-ebc6c3d4-0c14-11e8-8d28-12859c9fd631.png)

this is when i run start
![default](https://user-images.githubusercontent.com/15883911/35902153-097d05d2-0c15-11e8-8101-4b4fc4df5d79.png)

**Comment by nsilvah** [comment]
I have the same problem

**Comment by davidchong** [comment]
Exact same problem!

**Comment by tmcw** [comment]
Same issue as #64
