### ISSUE TITLE
Show examples in not working after build

### ISSUE THREAD

**Issue by fadijabi** [tmcw/docbox#81]
Hi,

I deployed docbox locally using npm run build and everything works just fine. However, "Show examples in: cURL cli Python JS Java ObjC Swift" toggles are not working. 

Toggles are working fine using npm start. 

Any clue why when deployed locally toggles are not working?

**Comment by tmcw** [comment]
Possibly you cloned docbox before [feb 22](https://github.com/tmcw/docbox/issues/64), when a fix for publishing was rolled out?

**Comment by fadfood** [comment]
Not really. I cloned recently and still same problem

**Comment by fadijabi** [comment]
Hi again, any update on this issue?

Note: the issue happens only when I run the build. If I do **npm start** it works as expected. 
Also running the build the second time for updating the content, the documentations becomes a mess. I have to reset the index page to the empty one and run the build again.
